name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  id-token: write  # Required for OIDC
  contents: write  # for softprops/action-gh-release to create GitHub release

jobs:
  build:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@6e7bdbda5fe05107efc88b23b7ed00aa05f84ca0
        with:
          standalone: true
      - name: Setup Node
        run: pnpm env use -g 24.11.1
        timeout-minutes: 1
      - name: pnpm install
        run: pnpm install
      - name: Publish Packages
        run: pnpm publish --no-git-checks
